version: $(VERSION) (#{build})
skip_non_tags: true
clone_depth: 1
environment:
  JAVA_HOME: C:\Program Files\Java\jdk21
  VERSION: 0.4.0+1.21
  MODRINTH_TOKEN:
    secure: bfjh/wWW2wVw0atTgZDwcelyOBIN6lt+UGMHk3KZtlbED4wmjuadyGEXWV8wF63LVfvO40GKqvZKJul1Uy6XdU53K1Zvw0IEVV0iT3lWjKQ= #已过期，将于重构完成时替换
  CURSEFORGE_API_KEY:
    secure: /RPZ/RoQddhnUHnXdS5JqC84Pe/yERje6+Dc/1KEiXnnckybjPBSvynyHNujYB17 #已过期，将于重构完成时替换
cache:
  - C:\Users\appveyor\.gradle\caches\fabric-loom
  - C:\Users\appveyor\.gradle\caches\modules-2
build_script:
  - cmd: >-
      gradlew build --no-daemon
      
      gradlew curseforge --no-daemon
      
      gradlew modrinth --no-daemon
artifacts:
  - path: .\build\libs\Ultimate-Scaler-$(VERSION).jar
    name: UltimateScaler-$(VERSION).jar
  - path: .\build\libs\Ultimate-Scaler-$(VERSION)-sources.jar
    name: UltimateScaler-$(VERSION)-sources.jar
deploy:
  - provider: GitHub
    tag: v$(VERSION)
    release: $(VERSION)
    description:
    auth_token:
      secure: mIxbyFSpUuMyOA9YhYQO55Y5v2HzI49xxtm1MjiCHuqRfKXZhxE1znPZO+knOueMIuq6xI51zkpmKNENLAx60R5q0RufPptQvWjaTS/phRObFBrw8W/P3KEHmwS0cV5C #有效期至2026-09-12
    artifact: UltimateScaler-$(VERSION).jar
    draft: false
    prerelease: false
